import { describe, it, expect } from "vitest";
import * as fs from "node:fs/promises";
import * as path from "node:path";
import { spawnSync } from "node:child_process";

const REPO_ROOT = path.resolve(import.meta.dirname, "../../../..");
const GENERATED = path.join(
  REPO_ROOT,
  "packages/core/blueprint-data.generated.ts",
);
const SCRIPT = path.join(REPO_ROOT, "scripts/compile-blueprint.ts");

function runCompile(): void {
  const result = spawnSync("bun", ["run", SCRIPT], {
    cwd: REPO_ROOT,
    encoding: "utf8",
  });
  if (result.status !== 0) {
    throw new Error(
      `compile-blueprint failed: ${result.stderr}\n${result.stdout}`,
    );
  }
}

describe("compile-blueprint script", () => {
  it("emits a valid TS module from blueprint/rules/graph.yaml", async () => {
    runCompile();
    const content = await fs.readFile(GENERATED, "utf8");
    expect(content).toMatch(/Generated by scripts\/compile-blueprint\.ts/);
    expect(content).toMatch(/export const BLUEPRINT_DATA/);
    expect(content).toMatch(/export interface BlueprintSource/);
    const matches = content.match(/"ruleId"/g);
    expect(matches).not.toBeNull();
    expect(matches!.length).toBeGreaterThan(100);
  });

  it("is deterministic: two consecutive runs produce byte-identical output", async () => {
    runCompile();
    const first = await fs.readFile(GENERATED, "utf8");
    runCompile();
    const second = await fs.readFile(GENERATED, "utf8");
    expect(second).toBe(first);
  });
});
