import { Buffer } from "node:buffer";
import { afterAll, afterEach, beforeAll, describe, expect, it } from "vitest";
import { http, HttpResponse } from "msw";
import { setupServer } from "msw/node";

import { openPullRequest } from "../../github/pull-request.ts";
import type { GitHubHttpDeps } from "../../github/types.ts";
import branchRefBase from "../fixtures/github/branch-ref-base.json" with { type: "json" };
import filePut from "../fixtures/github/file-put.json" with { type: "json" };
import prCreated from "../fixtures/github/pr-created.json" with { type: "json" };

const BASE = "https://api.github.com";
const REPO = "test-org/test-repo";

const server = setupServer();

beforeAll(() => server.listen({ onUnhandledRequest: "error" }));
afterEach(() => server.resetHandlers());
afterAll(() => server.close());

function makeDeps(): GitHubHttpDeps {
  return {
    fetch: globalThis.fetch,
    getToken: async () => "test-token",
  };
}

describe("openPullRequest", () => {
  it("creates branch from base, commits files, and opens PR", async () => {
    const filesPut: Record<string, { contentBase64: string; sha?: string }> =
      {};
    let createdRef: { ref?: string; sha?: string } | null = null;
    let prBody: {
      title?: string;
      body?: string;
      head?: string;
      base?: string;
    } | null = null;

    server.use(
      // branch ref lookups
      http.get(
        `${BASE}/repos/${REPO}/git/ref/heads/superfield%2Fdeploy-workflow`,
        () =>
          HttpResponse.json({ message: "Not Found" }, { status: 404 }),
      ),
      http.get(`${BASE}/repos/${REPO}/git/ref/heads/main`, () =>
        HttpResponse.json(branchRefBase),
      ),
      // create ref
      http.post(`${BASE}/repos/${REPO}/git/refs`, async ({ request }) => {
        createdRef = (await request.json()) as typeof createdRef;
        return HttpResponse.json(branchRefBase, { status: 201 });
      }),
      // file existence checks (404 → new files)
      http.get(`${BASE}/repos/${REPO}/contents/:path*`, () =>
        HttpResponse.json({ message: "Not Found" }, { status: 404 }),
      ),
      // file PUTs
      http.put(
        `${BASE}/repos/${REPO}/contents/:path*`,
        async ({ request, params }) => {
          const body = (await request.json()) as {
            content: string;
            sha?: string;
          };
          const path = (params.path as string[] | string | undefined) ?? "";
          const flat = Array.isArray(path) ? path.join("/") : path;
          filesPut[flat] = { contentBase64: body.content, sha: body.sha };
          return HttpResponse.json(filePut, { status: 201 });
        },
      ),
      // open PR
      http.post(`${BASE}/repos/${REPO}/pulls`, async ({ request }) => {
        prBody = (await request.json()) as typeof prBody;
        return HttpResponse.json(prCreated, { status: 201 });
      }),
    );

    const result = await openPullRequest(
      REPO,
      "superfield/deploy-workflow",
      "main",
      "feat: add deploy workflow",
      "Generated by superfield sync",
      makeDeps(),
      {
        files: [
          {
            path: ".github/workflows/deploy.yml",
            content: "name: deploy\non: workflow_dispatch\n",
          },
        ],
      },
    );

    expect(result).toEqual({
      number: 42,
      url: "https://github.com/test-org/test-repo/pull/42",
    });
    expect(createdRef).toEqual({
      ref: "refs/heads/superfield/deploy-workflow",
      sha: branchRefBase.object.sha,
    });
    expect(prBody).toEqual({
      title: "feat: add deploy workflow",
      body: "Generated by superfield sync",
      head: "superfield/deploy-workflow",
      base: "main",
    });
    expect(filesPut[".github/workflows/deploy.yml"]).toBeDefined();
    const decoded = Buffer.from(
      filesPut[".github/workflows/deploy.yml"]!.contentBase64,
      "base64",
    ).toString("utf8");
    expect(decoded).toBe("name: deploy\non: workflow_dispatch\n");
  });

  it("reuses an existing branch instead of creating one", async () => {
    let createRefCalled = false;
    server.use(
      http.get(`${BASE}/repos/${REPO}/git/ref/heads/feature%2Fexisting`, () =>
        HttpResponse.json({
          ref: "refs/heads/feature/existing",
          object: { sha: "deadbeef", type: "commit" },
        }),
      ),
      http.post(`${BASE}/repos/${REPO}/git/refs`, () => {
        createRefCalled = true;
        return HttpResponse.json({});
      }),
      http.post(`${BASE}/repos/${REPO}/pulls`, () =>
        HttpResponse.json(prCreated, { status: 201 }),
      ),
    );

    const result = await openPullRequest(
      REPO,
      "feature/existing",
      "main",
      "title",
      "body",
      makeDeps(),
    );
    expect(result.number).toBe(42);
    expect(createRefCalled).toBe(false);
  });
});
