#!/usr/bin/env bun
/**
 * @file embed-assets.ts
 *
 * Code-gen script: walks packages/control/apps/dist/ and writes
 * packages/control/src/embedded-assets.gen.ts.
 *
 * Each file is imported with `{ type: "file" }` so that `bun build --compile`
 * embeds the file content directly in the superfield binary. At runtime Bun
 * extracts each embedded file to a temp path; we serve it via Bun.file().
 *
 * Run after every Vite build:
 *   bun packages/control/scripts/embed-assets.ts
 */

import { existsSync, readdirSync, statSync, writeFileSync } from "fs";
import { join, relative } from "path";

const distDir = join(import.meta.dir, "../apps/dist");
const genFile = join(import.meta.dir, "../src/embedded-assets.gen.ts");

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

const files = existsSync(distDir) ? walk(distDir) : [];

const importLines: string[] = [];
const mapEntries: string[] = [];

let i = 0;
for (const abs of files) {
  // URL path key: /index.html, /assets/index-abc.js, etc.
  const urlPath = "/" + relative(distDir, abs).replace(/\\/g, "/");
  // Import path relative to src/
  const importPath = "../apps/dist" + urlPath;
  const varName = `_a${i}`;
  importLines.push(
    `import ${varName} from ${JSON.stringify(importPath)} with { type: "file" };`,
  );
  mapEntries.push(`  [${JSON.stringify(urlPath)}, ${varName}]`);
  i++;
}

const mapBody = mapEntries.length > 0 ? `\n${mapEntries.join(",\n")},\n` : "";

const src = `// AUTO-GENERATED by scripts/embed-assets.ts — do not edit manually.
// Re-run after every Vite build: bun packages/control/scripts/embed-assets.ts
${importLines.join("\n")}

/**
 * Maps URL path (e.g. "/index.html") to a Bun-embedded file path.
 * In a compiled binary each value is a temp path Bun extracts at startup.
 * In source/dev mode each value is the literal file path in the dist directory.
 */
export const embeddedAssets: ReadonlyMap<string, string> = new Map([${mapBody}]);
`;

writeFileSync(genFile, src, "utf8");
console.log(`[embed-assets] wrote ${files.length} entries → ${genFile}`);
