# Vendored superfield workflow template.
#
# Substitutions performed by `syncWorkflows()`:
#   {{ APP_NAME }}     — application name
#   {{ IMAGE_REPO }}   — full image repo, e.g. ghcr.io/owner/repo
#   {{ DEPLOYMENTS }}  — comma-separated k8s deployment names; expanded into
#                        the `kubectl set image` + rollout-status loop below.
#
# Per-environment secrets consumed (created by `superfield setup-github`):
#   DEPLOY_HOST_<ENV>, DEPLOY_KEY_<ENV>, DATABASE_URL_<ENV>,
#   WEBHOOK_SECRET_<ENV>, COOKIE_SECRET_<ENV>
#
# DO NOT EDIT THIS FILE IN-PLACE inside an application repo. Re-run
# `superfield sync` to regenerate.
name: deploy

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Image tag to deploy (e.g. v1.2.3 or sha-<commit>)"
        required: true
        type: string
      environment:
        description: "Target environment"
        required: true
        type: choice
        options:
          - demo
          - staging
          - prod

permissions:
  contents: read
  packages: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      APP_NAME: "{{ APP_NAME }}"
      IMAGE_REPO: "{{ IMAGE_REPO }}"
      DEPLOYMENTS: "{{ DEPLOYMENTS }}"
      IMAGE_TAG: ${{ inputs.image_tag }}
      ENV_NAME: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Resolve env-scoped secrets
        id: secrets
        env:
          DEPLOY_HOST_DEMO: ${{ secrets.DEPLOY_HOST_DEMO }}
          DEPLOY_HOST_STAGING: ${{ secrets.DEPLOY_HOST_STAGING }}
          DEPLOY_HOST_PROD: ${{ secrets.DEPLOY_HOST_PROD }}
          DEPLOY_KEY_DEMO: ${{ secrets.DEPLOY_KEY_DEMO }}
          DEPLOY_KEY_STAGING: ${{ secrets.DEPLOY_KEY_STAGING }}
          DEPLOY_KEY_PROD: ${{ secrets.DEPLOY_KEY_PROD }}
          DATABASE_URL_DEMO: ${{ secrets.DATABASE_URL_DEMO }}
          DATABASE_URL_STAGING: ${{ secrets.DATABASE_URL_STAGING }}
          DATABASE_URL_PROD: ${{ secrets.DATABASE_URL_PROD }}
        run: |
          UP=$(echo "$ENV_NAME" | tr '[:lower:]' '[:upper:]')
          host_var="DEPLOY_HOST_${UP}"
          key_var="DEPLOY_KEY_${UP}"
          db_var="DATABASE_URL_${UP}"
          echo "host=${!host_var}" >> "$GITHUB_OUTPUT"
          echo "::add-mask::${!key_var}"
          mkdir -p ~/.ssh
          printf '%s\n' "${!key_var}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo "db=${!db_var}" >> "$GITHUB_OUTPUT"

      - name: Resolve image tag to digest (GHCR)
        id: digest
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Strip the registry hostname from IMAGE_REPO to get owner/repo path
          PKG_PATH="${IMAGE_REPO#ghcr.io/}"
          OWNER="${PKG_PATH%%/*}"
          NAME="${PKG_PATH#*/}"
          TOKEN=$(printf '%s' "$GH_TOKEN" | base64)
          MANIFEST=$(curl -sSL -H "Authorization: Bearer ${TOKEN}" \
            -H "Accept: application/vnd.oci.image.index.v1+json,application/vnd.docker.distribution.manifest.v2+json" \
            -D /tmp/h.txt \
            "https://ghcr.io/v2/${OWNER}/${NAME}/manifests/${IMAGE_TAG}")
          DIGEST=$(grep -i '^docker-content-digest:' /tmp/h.txt | awk '{print $2}' | tr -d '\r')
          if [ -z "$DIGEST" ]; then
            echo "::error::Could not resolve digest for ${IMAGE_REPO}:${IMAGE_TAG}"
            exit 1
          fi
          echo "digest=${DIGEST}" >> "$GITHUB_OUTPUT"

      - name: Add SSH host
        env:
          HOST: ${{ steps.secrets.outputs.host }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts 2>/dev/null

      - name: Apply migration job
        env:
          HOST: ${{ steps.secrets.outputs.host }}
          DIGEST: ${{ steps.digest.outputs.digest }}
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=yes "deploy@${HOST}" bash -s <<EOF
          set -euo pipefail
          cat <<'JOB' | kubectl apply -f -
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: ${APP_NAME}-migrate-${GITHUB_RUN_ID}
            namespace: ${ENV_NAME}
          spec:
            backoffLimit: 0
            template:
              spec:
                restartPolicy: Never
                containers:
                  - name: migrate
                    image: ${IMAGE_REPO}@${DIGEST}
                    command: ["/${APP_NAME}", "migrate"]
          JOB
          kubectl -n "${ENV_NAME}" wait --for=condition=complete \
            --timeout=10m "job/${APP_NAME}-migrate-${GITHUB_RUN_ID}"
          EOF

      - name: Roll out app + workers
        id: rollout
        env:
          HOST: ${{ steps.secrets.outputs.host }}
          DIGEST: ${{ steps.digest.outputs.digest }}
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=yes "deploy@${HOST}" bash -s <<EOF
          set -euo pipefail
          IFS=',' read -ra DEPS <<< "${DEPLOYMENTS}"
          for d in "\${DEPS[@]}"; do
            kubectl -n "${ENV_NAME}" set image "deployment/\$d" \
              "*=${IMAGE_REPO}@${DIGEST}"
          done
          for d in "\${DEPS[@]}"; do
            kubectl -n "${ENV_NAME}" rollout status "deployment/\$d" --timeout=10m
          done
          EOF

      - name: Health gate
        id: health
        env:
          HOST: ${{ steps.secrets.outputs.host }}
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=yes "deploy@${HOST}" \
            "kubectl -n '${ENV_NAME}' run healthz-${GITHUB_RUN_ID} --rm -i --restart=Never \
              --image=curlimages/curl:8.10.1 --command -- \
              curl -fsS --max-time 10 'http://${APP_NAME}.${ENV_NAME}.svc.cluster.local/healthz'"

      - name: Roll back on failure
        if: failure() && steps.rollout.outcome == 'success'
        env:
          HOST: ${{ steps.secrets.outputs.host }}
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=yes "deploy@${HOST}" bash -s <<EOF
          set -euo pipefail
          IFS=',' read -ra DEPS <<< "${DEPLOYMENTS}"
          for d in "\${DEPS[@]}"; do
            kubectl -n "${ENV_NAME}" rollout undo "deployment/\$d" || true
          done
          EOF

      - name: Annotate deployment
        if: always()
        env:
          DIGEST: ${{ steps.digest.outputs.digest }}
          OUTCOME: ${{ job.status }}
        run: |
          echo "deployed ${IMAGE_REPO}@${DIGEST} to ${ENV_NAME}: ${OUTCOME}"
