# Vendored superfield workflow template.
#
# Substitutions performed by `syncWorkflows()`:
#   {{ APP_NAME }}     — application name (used for binary + image names)
#   {{ IMAGE_REPO }}   — full image repo, e.g. ghcr.io/owner/repo
#   {{ DEPLOYMENTS }}  — comma-separated k8s deployment names (unused here)
#
# DO NOT EDIT THIS FILE IN-PLACE inside an application repo. Re-run
# `superfield sync` to regenerate.
name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install deps
        run: bun install --frozen-lockfile

      - name: Run tests
        run: bun test

      - name: Build native binary
        run: |
          mkdir -p dist
          bun build --compile --target=bun-linux-x64 \
            --outfile dist/{{ APP_NAME }} \
            ./packages/{{ APP_NAME }}/index.ts

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute tags
        id: tags
        run: |
          SEMVER="${GITHUB_REF_NAME}"
          SHA_TAG="sha-${GITHUB_SHA}"
          echo "semver=${SEMVER}" >> "$GITHUB_OUTPUT"
          echo "sha_tag=${SHA_TAG}" >> "$GITHUB_OUTPUT"

      - name: Build and push image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            {{ IMAGE_REPO }}:${{ steps.tags.outputs.semver }}
            {{ IMAGE_REPO }}:${{ steps.tags.outputs.sha_tag }}
          provenance: false
          file: ./Dockerfile

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tags.outputs.semver }}
          name: ${{ steps.tags.outputs.semver }}
          body: |
            Image: `{{ IMAGE_REPO }}:${{ steps.tags.outputs.semver }}`
            Digest: `${{ steps.build.outputs.digest }}`
            SHA tag: `{{ IMAGE_REPO }}:${{ steps.tags.outputs.sha_tag }}`
