# Vendored superfield workflow template.
#
# Substitutions performed by `syncWorkflows()`:
#   {{ APP_NAME }}     — application name (informational)
#   {{ IMAGE_REPO }}   — full image repo (unused, kept for symmetry)
#   {{ DEPLOYMENTS }}  — comma-separated k8s deployment names; each gets
#                        an independent `kubectl rollout undo`.
#
# Per-environment secrets consumed:
#   DEPLOY_HOST_<ENV>, DEPLOY_KEY_<ENV>
#
# DO NOT EDIT THIS FILE IN-PLACE inside an application repo. Re-run
# `superfield sync` to regenerate.
name: rollback

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        type: choice
        options:
          - demo
          - staging
          - prod

permissions:
  contents: read

jobs:
  rollback:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      APP_NAME: "{{ APP_NAME }}"
      DEPLOYMENTS: "{{ DEPLOYMENTS }}"
      ENV_NAME: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Resolve env-scoped secrets
        id: secrets
        env:
          DEPLOY_HOST_DEMO: ${{ secrets.DEPLOY_HOST_DEMO }}
          DEPLOY_HOST_STAGING: ${{ secrets.DEPLOY_HOST_STAGING }}
          DEPLOY_HOST_PROD: ${{ secrets.DEPLOY_HOST_PROD }}
          DEPLOY_KEY_DEMO: ${{ secrets.DEPLOY_KEY_DEMO }}
          DEPLOY_KEY_STAGING: ${{ secrets.DEPLOY_KEY_STAGING }}
          DEPLOY_KEY_PROD: ${{ secrets.DEPLOY_KEY_PROD }}
        run: |
          UP=$(echo "$ENV_NAME" | tr '[:lower:]' '[:upper:]')
          host_var="DEPLOY_HOST_${UP}"
          key_var="DEPLOY_KEY_${UP}"
          echo "host=${!host_var}" >> "$GITHUB_OUTPUT"
          echo "::add-mask::${!key_var}"
          mkdir -p ~/.ssh
          printf '%s\n' "${!key_var}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Add SSH host
        env:
          HOST: ${{ steps.secrets.outputs.host }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts 2>/dev/null

      - name: Roll back deployments
        env:
          HOST: ${{ steps.secrets.outputs.host }}
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=yes "deploy@${HOST}" bash -s <<EOF
          set -euo pipefail
          IFS=',' read -ra DEPS <<< "${DEPLOYMENTS}"
          for d in "\${DEPS[@]}"; do
            kubectl -n "${ENV_NAME}" rollout undo "deployment/\$d"
            kubectl -n "${ENV_NAME}" rollout status "deployment/\$d" --timeout=10m
          done
          EOF
