// Generated by scripts/compile-blueprint.ts. Do not edit by hand.
//
// Scout placeholder (issue #77): feature work that actually emits real data
// lands in issue #78. Until then this file exports an empty, typed constant so
// downstream consumers can import it without runtime behaviour change.

import type { BlueprintGraphNode, BlueprintDomain } from "./blueprint.ts";

export interface BlueprintSource {
  nodes: BlueprintGraphNode[];
  domains: BlueprintDomain[];
  implementations: Record<string, string>;
}

export const BLUEPRINT_DATA: BlueprintSource = {
  nodes: [],
  domains: [],
  implementations: {},
};
