#!/usr/bin/env bun
/**
 * Compile the Superfield Blueprint (blueprint/rules/*.yaml) into a bundled
 * TypeScript module at packages/core/blueprint-data.generated.ts.
 *
 * Scout stub (issue #77): this is a no-op that rewrites the empty placeholder
 * so the script is wired end-to-end. Real compilation lands in issue #78.
 *
 * Run with: bun run blueprint:compile
 */
import * as fs from "node:fs/promises";
import * as path from "node:path";

const OUTPUT_REL = "packages/core/blueprint-data.generated.ts";

const PLACEHOLDER = `// Generated by scripts/compile-blueprint.ts. Do not edit by hand.
//
// Scout placeholder (issue #77): feature work that actually emits real data
// lands in issue #78. Until then this file exports an empty, typed constant so
// downstream consumers can import it without runtime behaviour change.

import type { BlueprintGraphNode, BlueprintDomain } from "./blueprint.ts";

export interface BlueprintSource {
  nodes: BlueprintGraphNode[];
  domains: BlueprintDomain[];
  implementations: Record<string, string>;
}

export const BLUEPRINT_DATA: BlueprintSource = {
  nodes: [],
  domains: [],
  implementations: {},
};
`;

async function main(): Promise<void> {
  const repoRoot = path.resolve(import.meta.dirname, "..");
  const outPath = path.join(repoRoot, OUTPUT_REL);
  await fs.writeFile(outPath, PLACEHOLDER, "utf8");
  console.log(`wrote placeholder ${OUTPUT_REL}`);
}

await main();
