#!/usr/bin/env bun
/**
 * Compile the Superfield Blueprint (blueprint/rules/*.yaml) into a bundled
 * TypeScript module at packages/core/blueprint-data.generated.ts.
 *
 * Reads graph.yaml, every blueprints/<domain>.yaml, and every file under
 * implementations/ts/, and emits a deterministic, typed constant so that the
 * compiled `superfield` binary can load the blueprint without shipping a
 * sidecar asset directory.
 *
 * Run with: bun run blueprint:compile
 *
 * CI staleness guard: the "Blueprint freshness" job in .github/workflows/build.yml
 * re-runs this script and fails if the generated file differs from what is
 * committed. This ensures graph.yaml / domain file changes are always accompanied
 * by a regenerated blueprint-data.generated.ts.
 */
import * as fs from "node:fs/promises";
import * as path from "node:path";
import { parse as parseYaml } from "yaml";

const OUTPUT_REL = "packages/core/blueprint-data.generated.ts";

type RuleType =
  | "threat"
  | "principle"
  | "design_pattern"
  | "architecture"
  | "checklist"
  | "antipattern";

interface GraphNodeOut {
  hash: string;
  ruleId: string;
  name: string;
  type: RuleType;
  domain: string;
  sourceFile: string;
}

interface DomainRuleOut {
  number: string;
  hash: string;
  name: string;
  type: RuleType;
  description: string;
  deprecated: boolean;
}

interface DomainOut {
  name: string;
  title: string;
  vision: string;
  rules: DomainRuleOut[];
}

const KNOWN_DOMAINS = [
  "arch",
  "auth",
  "data",
  "deploy",
  "env",
  "etl",
  "imap-etl",
  "process",
  "prune",
  "task-queue",
  "test",
  "ux",
  "worker",
];

async function readGraph(blueprintDir: string): Promise<{
  corpusVersion: number;
  generated: string;
  ruleCount: number;
  nodes: GraphNodeOut[];
}> {
  const graphPath = path.join(blueprintDir, "rules", "graph.yaml");
  const raw = await fs.readFile(graphPath, "utf8");
  const parsed = parseYaml(raw, { uniqueKeys: false }) as {
    corpus_version: number;
    generated: string;
    rule_count: number;
    nodes: Record<string, [string, string, string, string, string]>;
  };

  const nodes: GraphNodeOut[] = Object.entries(parsed.nodes).map(
    ([hash, tuple]) => ({
      hash,
      ruleId: tuple[0],
      name: tuple[1],
      type: tuple[2] as RuleType,
      domain: tuple[3].toLowerCase(),
      sourceFile: tuple[4],
    }),
  );

  // Stable order: by ruleId then hash.
  nodes.sort((a, b) => {
    if (a.ruleId !== b.ruleId) return a.ruleId < b.ruleId ? -1 : 1;
    return a.hash < b.hash ? -1 : 1;
  });

  return {
    corpusVersion: parsed.corpus_version,
    generated: parsed.generated,
    ruleCount: parsed.rule_count,
    nodes,
  };
}

async function readDomains(blueprintDir: string): Promise<DomainOut[]> {
  const out: DomainOut[] = [];
  for (const domainName of [...KNOWN_DOMAINS].sort()) {
    const domainPath = path.join(
      blueprintDir,
      "rules",
      "blueprints",
      `${domainName}.yaml`,
    );
    let raw: string;
    try {
      raw = await fs.readFile(domainPath, "utf8");
    } catch {
      continue;
    }
    const parsed = parseYaml(raw) as {
      meta?: { domain?: string; title?: string; vision?: string };
      rules?: Array<{
        number: string;
        hash: string;
        name: string;
        type: RuleType;
        description: string;
        deprecated?: boolean;
      }>;
    };
    const rules = (parsed.rules ?? []).map((r) => ({
      number: r.number,
      hash: r.hash,
      name: r.name,
      type: r.type,
      description: r.description,
      deprecated: r.deprecated ?? false,
    }));
    // Stable order within a domain: by rule number.
    rules.sort((a, b) =>
      a.number < b.number ? -1 : a.number > b.number ? 1 : 0,
    );
    out.push({
      name: domainName,
      title: parsed.meta?.title ?? domainName,
      vision: parsed.meta?.vision ?? "",
      rules,
    });
  }
  return out;
}

async function readImplementations(
  blueprintDir: string,
): Promise<Record<string, string>> {
  const tsDir = path.join(blueprintDir, "rules", "implementations", "ts");
  const out: Record<string, string> = {};
  let entries: string[];
  try {
    entries = await fs.readdir(tsDir);
  } catch {
    return out;
  }
  for (const entry of entries.sort()) {
    const full = path.join(tsDir, entry);
    const stat = await fs.stat(full);
    if (!stat.isFile()) continue;
    out[entry] = await fs.readFile(full, "utf8");
  }
  // Return already key-sorted via insertion order.
  const sorted: Record<string, string> = {};
  for (const k of Object.keys(out).sort()) {
    const v = out[k];
    if (v !== undefined) sorted[k] = v;
  }
  return sorted;
}

function emit(
  meta: { corpusVersion: number; generated: string; ruleCount: number },
  nodes: GraphNodeOut[],
  domains: DomainOut[],
  implementations: Record<string, string>,
): string {
  const header = `// Generated by scripts/compile-blueprint.ts. Do not edit by hand.
//
// This file is the compiled form of blueprint/rules/ used by the bundled
// \`superfield\` binary. Regenerate with \`bun run blueprint:compile\`.

import type { BlueprintGraphNode, BlueprintDomain } from "./blueprint.ts";

export interface BlueprintSource {
  corpusVersion: number;
  generated: string;
  ruleCount: number;
  nodes: BlueprintGraphNode[];
  domains: BlueprintDomain[];
  implementations: Record<string, string>;
}

`;

  const payload = {
    corpusVersion: meta.corpusVersion,
    generated: meta.generated,
    ruleCount: meta.ruleCount,
    nodes,
    domains: domains.map((d) => ({
      name: d.name,
      title: d.title,
      vision: d.vision,
      rules: d.rules,
    })),
    implementations,
  };

  // JSON.stringify with sorted keys for determinism.
  const json = stableStringify(payload, 2);

  return `${header}export const BLUEPRINT_DATA: BlueprintSource = ${json} as unknown as BlueprintSource;\n`;
}

function stableStringify(value: unknown, indent: number): string {
  const seen = new WeakSet<object>();
  const replacer = (_key: string, v: unknown): unknown => {
    if (v && typeof v === "object" && !Array.isArray(v)) {
      if (seen.has(v as object)) return v;
      seen.add(v as object);
      const sorted: Record<string, unknown> = {};
      for (const k of Object.keys(v as Record<string, unknown>).sort()) {
        sorted[k] = (v as Record<string, unknown>)[k];
      }
      return sorted;
    }
    return v;
  };
  return JSON.stringify(value, replacer, indent);
}

async function main(): Promise<void> {
  const repoRoot = path.resolve(import.meta.dirname, "..");
  const blueprintDir = path.join(repoRoot, "blueprint");

  const { corpusVersion, generated, ruleCount, nodes } =
    await readGraph(blueprintDir);
  const domains = await readDomains(blueprintDir);
  const implementations = await readImplementations(blueprintDir);

  const source = emit(
    { corpusVersion, generated, ruleCount },
    nodes,
    domains,
    implementations,
  );

  const outPath = path.join(repoRoot, OUTPUT_REL);
  await fs.writeFile(outPath, source, "utf8");
  console.log(
    `wrote ${OUTPUT_REL} (${nodes.length} nodes, ${domains.length} domains, ${Object.keys(implementations).length} impl files)`,
  );
}

await main();
