name: Integration Tests

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "docs/**"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "docs/**"

jobs:
  test-integration:
    name: Integration (API) tests
    runs-on: [self-hosted, Linux, X64]
    container:
      image: mcr.microsoft.com/devcontainers/base:bookworm
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bun --bun vitest run packages/*/tests/integration
