name: Unit Tests

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "docs/**"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "docs/**"

jobs:
  test-unit:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout submodules
        run: |
          git config --global url."https://x-access-token:${{ github.token }}@github.com/".insteadOf "https://github.com/"
          git submodule update --init --recursive
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bun --bun vitest run packages/*/tests/unit
